module.exports = {
    PROFILE: "PROFILE", //FOR THINGS LIKE BLACKLIST, BADGE AND ADDRESS
    SYSTEM: "SYSTEM", //FOR THINGS LIKE BUG REPORTING
    PAYMENT: "PAYMENT", // FOR WALLET RELATED ISSUES
    JIO: "JIO", // FOR JIO RELATED ISSUES
    REQUEST: "REQUEST", // FOR REQUEST RELATED ISSUES
    HEALTH: "HEALTH" // FOR ALL COVID-19 RELATED ISSUES
}